// Build a fax-ready orders summary from per-diagnosis plan text and open
// a print preview window. Used by the one-click PF export flow.

import {
  type ProviderSignature,
} from './providerInfo';

export interface OrdersSummaryInput {
  patientName: string;
  mrn: string;
  dob?: string;
  facility?: string;
  /** Legacy: provider display name. Prefer providerSignature. */
  provider?: string;
  providerSignature?: ProviderSignature;
  diagnoses: Array<{ code: string; description: string; plan: string }>;
  additionalOrders?: string[];
}

// Heuristic: split a plan block into discrete order lines.
// Keeps bulleted/numbered items; otherwise splits by line.
export function extractOrdersFromPlan(plan: string): string[] {
  if (!plan) return [];
  return plan
    .split(/\r?\n/)
    .map((l) =>
      l
        .replace(/^\s*[-*•]\s+/, '')
        .replace(/^\s*\d+[.)]\s+/, '')
        .trim()
    )
    .filter((l) => l.length > 0 && !/^(assessment|plan|continue plan|---)/i.test(l));
}

export function buildOrdersSummary(input: OrdersSummaryInput): {
  text: string;
  orders: string[];
} {
  const orders: string[] = [];
  for (const dx of input.diagnoses) {
    const lines = extractOrdersFromPlan(dx.plan);
    for (const l of lines) {
      const tag = dx.code ? `[${dx.code}] ` : '';
      orders.push(`${tag}${l}`);
    }
  }
  if (input.additionalOrders?.length) orders.push(...input.additionalOrders);

  const date = new Date().toLocaleDateString();
  const header = [
    'HOME MEDICAL SERVICES',
    'Mobile Primary Care — Orders Summary',
    `${input.patientName} · MRN ${input.mrn}${input.dob ? ` · DOB ${input.dob}` : ''}`,
    `Date: ${date}`,
    input.facility ? `Facility: ${input.facility}` : '',
  ]
    .filter(Boolean)
    .join('\n');

  const body = orders.map((o, i) => `${i + 1}. ${o}`).join('\n');
  return { text: `${header}\n\n${body}`, orders };
}

export function openOrdersPrintWindow(input: OrdersSummaryInput) {
  const { text, orders } = buildOrdersSummary(input);
  const w = window.open('', '_blank');
  if (!w) return { text, orders, opened: false };

  const dxRows = input.diagnoses
    .filter((d) => d.code || d.description)
    .map(
      (d) =>
        `<tr><td style="padding:4px 8px;border-bottom:1px solid #eee;font-family:monospace">${
          d.code || '—'
        }</td><td style="padding:4px 8px;border-bottom:1px solid #eee">${d.description || ''}</td></tr>`
    )
    .join('');

  w.document.write(`<!doctype html><html><head><title>Orders — ${input.patientName}</title>
<style>
  body{font-family:Arial,sans-serif;padding:40px;max-width:720px;color:#111}
  h1{font-size:18px;margin:0 0 4px}
  .meta{font-size:13px;color:#444;margin-bottom:16px}
  .section{margin-top:18px}
  .section h2{font-size:13px;text-transform:uppercase;letter-spacing:.05em;color:#555;margin:0 0 6px;border-bottom:1px solid #000;padding-bottom:4px}
  ol{margin:6px 0 0 20px;padding:0}
  li{margin:3px 0;font-size:13px}
  table{border-collapse:collapse;width:100%;font-size:12px;margin-top:4px}
  .footer{margin-top:32px;border-top:1px solid #ccc;padding-top:8px;font-size:11px;color:#666}
</style></head><body>
  <div style="display:flex;align-items:center;gap:16px;border-bottom:2px solid #0f3a5f;padding-bottom:10px;margin-bottom:14px">
    <img src="${window.location.origin}/hms-logo.webp" alt="Home Medical Services" style="height:70px;width:auto;display:block" />
    <div style="font-size:12px;color:#475569">Mobile Primary Care &middot; Orders / Fax Summary</div>
  </div>
  <div class="meta">
    <div><strong>${input.patientName}</strong> · MRN ${input.mrn}${
      input.dob ? ` · DOB ${input.dob}` : ''
    }</div>
    <div>Date: ${new Date().toLocaleDateString()}</div>
    ${input.facility ? `<div>Facility: ${input.facility}</div>` : ''}
  </div>

  ${
    dxRows
      ? `<div class="section"><h2>Active Diagnoses</h2>
      <table>${dxRows}</table></div>`
      : ''
  }

  <div class="section"><h2>Orders</h2>
    ${orders.length ? `<ol>${orders.map((o) => `<li>${o}</li>`).join('')}</ol>` : '<p><em>No discrete orders found in plan.</em></p>'}
  </div>

  <div class="footer">Generated by Chart Flo · ${new Date().toLocaleString()}</div>
  <script>window.onload=()=>window.print();</script>
</body></html>`);
  w.document.close();
  return { text, orders, opened: true };
}
